<%@ Page Title="" Language="C#" MasterPageFile="~/ana.master" AutoEventWireup="true" CodeFile="Künye.aspx.cs" Inherits="Künye" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <section class="container">
        <div class="detailp"> <p> </p><p style="text-align: center;"><strong>&nbsp;</strong><em><strong>İmtiyaz Sahibi / Grantee&nbsp;</strong></em><br><u><em>Özen Medya&nbsp;Reklam ve Tanıtım Hizmetleri</em></u><br><em><strong>Adres / Contact and Address Information</strong></em><br>Nefise Sultan Mahallesi 2. İstasyon Caddesi No:65/B<br>Merkez/KARAMAN<br><em><strong>Genel Yayın Yönetmeni /&nbsp;Editor in Chief</strong></em><br>Hasan Erkin ÖZEN<br><em><strong>Sorumlu Yazı İşleri Müdürü / Responsible Editor</strong></em><br>Ünsal Furkan HARANİ<br><em><strong>Haber Koordinatörü / News Coordinator</strong></em><br>Mert ÖZDİPİ<br><em><strong>Editörler /&nbsp;Editors</strong></em><br>Mustafa BÜLBÜL<br>Oktay EKMEN</p><p style="text-align: center;"><em><strong>Görsel Program İçerik Sorumlusu /&nbsp;Visual Program Content Officer</strong></em></p><p style="text-align: center;">Furkan KARHARMAN</p><p style="text-align: center;">&nbsp;</p><p style="text-align: center;"><em><strong>Hukuk Danışmanı / Legal Advisor</strong></em><br>Av. Hüseyin MUTLU<br>Av. Erdal YILMAZ<br><em><strong>Mali Müşavir / Financial Advisor</strong></em><br>Yasin GÜNAY<br><strong>Firma Bilgisi /&nbsp;Company Information</strong><br><u>ÖZEN&nbsp;MEDYA REKLAM ve TANITIM HİZMETLERİ</u><br>KARAMAN VD.<br>Nefise Sultan Mahallesi 2. İstasyon Caddesi No:65/B<br>Merkez/KARAMAN<br><strong>bilgi@e-karaman.com</strong><br><strong>0507 404 62 17</strong><br><strong>Yazılım /&nbsp;Software</strong><br>Tumeva Bilişim<br>&nbsp;<br>Gizlilik Politikası / Privacy Policy<br>© Copyrigth 2006&nbsp;E-karaman.com tüm hakları saklıdır. Kod, haber, resim, röportaj gibi her türlü içeriğinin tüm telif hakları E-karaman.com’a aittir. E-karaman.com sitesinde yer alan bütün yazılar, materyaller, resimler, ses dosyaları, animasyonlar, videolar, dizayn, tasarım ve düzenlemelerimizin telif hakları 5846 numaralı yasa telif hakları korunmaktadır. BunlarE-karaman.com'un yazılı izni olmaksızın ticari olarak herhangi bir şekilde kopyalanamaz, dağıtılamaz, değiştirilemez, yayınlanamaz. İzinsiz ve kaynak belirtilmeksizin kopyalama ve kullanımı yapılamaz.<br>E-karaman.com’daki harici linkler ayrı bir sayfada açılır. Yayınlanan yazı ve yorumlardan yazarları sorumludur. E-karaman.com’da hiçbir bildirim yapmadan, herhangi bir zaman değişikliğe gidebilir. Bu sitedeki bilgilerden kaynaklı hataların hiçbirinden sorumlu değildir.<br>&nbsp;<br>Sitede yayımlanan Köşe Yazıları ve Yorumların sorumluluğu yazarlarına aittir.<br>E-karaman.com yazıların sorumluluğunu almaz.<br>Sitedeki tüm harici linkler ayrı bir sayfada açılır.<br>&nbsp;<br>E-karaman.com harici linklerin sorumluluğunu almaz.</p> <p></p> </div>
    </section>
</asp:Content>

